name: Bug Report
description: Report a bug
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you see?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: Describe expected behavior
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS / Compiler / Version
