function(enable_clang_tidy)
  find_program(CLANG_TIDY_EXE NAMES clang-tidy)
  if(CLANG_TIDY_EXE)
    set(CMAKE_CXX_CLANG_TIDY "${CLANG_TIDY_EXE}" PARENT_SCOPE)
  else()
    message(STATUS "clang-tidy not found")
  endif()
endfunction()

function(enable_cppcheck)
  find_program(CPPCHECK_EXE NAMES cppcheck)
  if(CPPCHECK_EXE)
    set(CMAKE_CXX_CPPCHECK "${CPPCHECK_EXE};--enable=warning,style,performance,portability;--inline-suppr" PARENT_SCOPE)
  else()
    message(STATUS "cppcheck not found")
  endif()
endfunction()
